In [1]:
from qililab.instrument_controllers.qblox_cluster_controller import QbloxClusterController
from qililab.instrument_controllers.qblox_spi_rack_controller import QbloxSPIRackController
from qililab.instrument_controllers.qdevil_qdac2_controller import QDevilQDAC2Controller
from qililab.instruments.qblox_d5a import QbloxD5A
from qililab.instruments.qblox_qcm import QbloxQCM
from qililab.instruments.qblox_qcm_rf import QbloxQCMRF
from qililab.instruments.qblox_qrm import QbloxQRM
from qililab.instruments.qblox_qrm_rf import QbloxQRMRF
from qililab.instruments.qblox_s4g import QbloxS4G
from qililab.instruments.qdevil_qdac2 import QDevilQDAC2
from qililab.instruments.rohde_schwarz_sg100 import RohdeSchwarzSG100
from qililab.runcard import Runcard
from qililab.settings.instrument_controllers import (
    QbloxClusterControllerSettings,
    QbloxSPIRackControllerSettings,
    QDevilQDAC2ControllerSettings,
)
from qililab.typings.enums import Parameter
from qililab.waveforms import Arbitrary, Gaussian

2024-11-25 15:00:19,852 - qm - INFO     - Starting session: 2d5ae3f0-fab2-4735-a4b1-17a3899309ac


In [2]:
gaussian = Gaussian(amplitude=1.0, duration=10_000, num_sigmas=0.5)
len(gaussian.envelope()), gaussian.envelope()

(10000,
 array([0.8824969 , 0.88254102, 0.88258514, ..., 0.88262925, 0.88258514,
        0.88254102]))

In [3]:
len(gaussian.envelope(resolution=1000)), gaussian.envelope(resolution=1000)

(10,
 array([0.8824969 , 0.92311635, 0.95599748, 0.98019867, 0.99501248,
        1.        , 0.99501248, 0.98019867, 0.95599748, 0.92311635]))

In [ ]:
import numpy as np

arb = Arbitrary(samples=np.linspace(0, 10_000, num=10_001, endpoint=True))
len(arb.envelope()), arb.envelope()

(10000,
 array([0.00000000e+00, 1.00010001e+00, 2.00020002e+00, ...,
        9.99799980e+03, 9.99899990e+03, 1.00000000e+04]))

In [9]:
len(arb.envelope(resolution=1000)), arb.envelope(resolution=1000)

(9990,
 array([1.53121960e-12, 1.00110121e+00, 2.00220242e+00, ...,
        9.99799780e+03, 9.99899890e+03, 1.00000000e+04]))

In [2]:
qcm = QbloxQCM()
qcm

QbloxQCM(settings=alias='qcm' timeout=1 outputs=[QbloxLFOutputSettings(port=0, offset=0.0), QbloxLFOutputSettings(port=1, offset=0.0), QbloxLFOutputSettings(port=2, offset=0.0), QbloxLFOutputSettings(port=3, offset=0.0)] sequencers=[QbloxSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=2, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=3, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offs

In [3]:
qcm_rf = QbloxQCMRF()
qcm_rf

QbloxQCMRF(settings=alias='qcm-rf' timeout=1 outputs=[QbloxRFOutputSettings(port=0, lo_enabled=True, lo_frequency=10000000000.0, attenuation=0.0, offset_i=0.0, offset_q=0.0), QbloxRFOutputSettings(port=1, lo_enabled=True, lo_frequency=10000000000.0, attenuation=0.0, offset_i=0.0, offset_q=0.0)] sequencers=[QbloxSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=2, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=3, outputs=[0], hardware_modulation=True, intermediate_frequency=5000000

In [4]:
qrm = QbloxQRM()
qrm

QbloxQRM(settings=alias='qrm' timeout=1 outputs=[QbloxLFOutputSettings(port=0, offset=0.0), QbloxLFOutputSettings(port=1, offset=0.0)] sequencers=[QbloxADCSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0, inputs=[0], hardware_demodulation=True, integration_length=1000, threshold=0.0, threshold_rotation=0.0, time_of_flight=0), QbloxADCSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0, inputs=[0], hardware_demodulation=True, integration_length=1000, threshold=0.0, threshold_rotation=0.0, time_of_flight=0), QbloxADCSequencerSettings(id=2, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0, inputs=

In [5]:
qrm_rf = QbloxQRMRF()
qrm_rf

QbloxQRMRF(settings=alias='qrm-rf' timeout=1 outputs=[QbloxRFOutputSettings(port=0, lo_enabled=True, lo_frequency=10000000000.0, attenuation=0.0, offset_i=0.0, offset_q=0.0)] sequencers=[QbloxADCSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0, inputs=[0], hardware_demodulation=True, integration_length=1000, threshold=0.0, threshold_rotation=0.0, time_of_flight=0), QbloxADCSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0, inputs=[0], hardware_demodulation=True, integration_length=1000, threshold=0.0, threshold_rotation=0.0, time_of_flight=0), QbloxADCSequencerSettings(id=2, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=

In [6]:
qdac2 = QDevilQDAC2()
qdac2

QDevilQDAC2(settings=alias='qdac2' dacs=[QDevilQDAC2ChannelSettings(id=0, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=1, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=2, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=3, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=4, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=5, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ram

In [7]:
second_qdac2 = QDevilQDAC2()
second_qdac2.settings.alias = "second_qdac2"

In [8]:
sg100 = RohdeSchwarzSG100()
sg100

RohdeSchwarzSG100(settings=alias='sg100' power=0.0 frequency=1000000000.0 rf_on=False)

In [9]:
s4g = QbloxS4G()
s4g

QbloxS4G(settings=alias='s4g' dacs=[QbloxS4GChannelSettings(id=0, current=0.0, span=<QbloxS4gSpan.MIN_BI: 'min_bi'>, ramping_enabled=True, ramping_rate=0.001), QbloxS4GChannelSettings(id=1, current=0.0, span=<QbloxS4gSpan.MIN_BI: 'min_bi'>, ramping_enabled=True, ramping_rate=0.001), QbloxS4GChannelSettings(id=2, current=0.0, span=<QbloxS4gSpan.MIN_BI: 'min_bi'>, ramping_enabled=True, ramping_rate=0.001), QbloxS4GChannelSettings(id=3, current=0.0, span=<QbloxS4gSpan.MIN_BI: 'min_bi'>, ramping_enabled=True, ramping_rate=0.001)])

In [10]:
d5a = QbloxD5A()
d5a

QbloxD5A(settings=alias='d5a' dacs=[QbloxD5AChannelSettings(id=0, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=1, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=2, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=3, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=4, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=5, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=6, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=7, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), Qblo

In [11]:
loaded_instruments = [qcm, qrm, qcm_rf, qrm_rf, qdac2, second_qdac2, sg100, s4g, d5a]

In [12]:
qdac2_controller = QDevilQDAC2Controller()
qdac2_controller.settings.modules.append({"alias": "qdac2", "slot": 1})
qdac2_controller

QDevilQDAC2Controller(settings=alias='qdac2_controller' connection=ConnectionSettings(type=<ConnectionType.TCP_IP: 'tcp_ip'>, address='168.0.0.1') modules=[{'alias': 'qdac2', 'slot': 1}] reset=True, modules=[])

In [13]:
spi_rack_controller = QbloxSPIRackController(
    settings=QbloxSPIRackControllerSettings(
        alias="spi-rack", modules=[{"alias": d5a.alias, "slot": 2}, {"alias": s4g.alias, "slot": 10}]
    ),
    loaded_instruments=loaded_instruments,
)
spi_rack_controller

QbloxSPIRackController(settings=alias='spi-rack' connection=ConnectionSettings(type=<ConnectionType.TCP_IP: 'tcp_ip'>, address='168.0.0.1') modules=[InstrumentModule(alias='d5a', slot=2), InstrumentModule(alias='s4g', slot=10)] reset=True, modules=[QbloxD5A(settings=alias='d5a' dacs=[QbloxD5AChannelSettings(id=0, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=1, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=2, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=3, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=4, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0.1), QbloxD5AChannelSettings(id=5, voltage=0.0, span=<QbloxD5ASpan.BI_2V: 'bi_2V'>, ramping_enabled=True, ramping_rate=0

In [14]:
qdac2_controller = QDevilQDAC2Controller(
    settings=QDevilQDAC2ControllerSettings(alias="qdac2_controller", modules=[{"alias": "qdac2", "slot": 0}]),
    loaded_instruments=loaded_instruments,
)
qdac2_controller

QDevilQDAC2Controller(settings=alias='qdac2_controller' connection=ConnectionSettings(type=<ConnectionType.TCP_IP: 'tcp_ip'>, address='168.0.0.1') modules=[InstrumentModule(alias='qdac2', slot=0)] reset=True, modules=[QDevilQDAC2(settings=alias='qdac2' dacs=[QDevilQDAC2ChannelSettings(id=0, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=1, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=2, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=3, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=4, voltage=

In [15]:
qblox_controller = QbloxClusterController(
    settings=QbloxClusterControllerSettings(
        alias="qblox_cluster",
        modules=[
            {"alias": qcm.alias, "slot": 0},
            {"alias": qrm.alias, "slot": 5},
            {"alias": qcm_rf.alias, "slot": 10},
            {"alias": qrm_rf.alias, "slot": 15},
        ],
    ),
    loaded_instruments=loaded_instruments,
)
qblox_controller

QbloxClusterController(settings=alias='qblox_cluster' connection=ConnectionSettings(type=<ConnectionType.TCP_IP: 'tcp_ip'>, address='168.0.0.1') modules=[InstrumentModule(alias='qcm', slot=0), InstrumentModule(alias='qrm', slot=5), InstrumentModule(alias='qcm-rf', slot=10), InstrumentModule(alias='qrm-rf', slot=15)] reset=True reference_clock=<ReferenceClock.INTERNAL: 'internal'>, modules=[QbloxQCM(settings=alias='qcm' timeout=1 outputs=[QbloxLFOutputSettings(port=0, offset=0.0), QbloxLFOutputSettings(port=1, offset=0.0), QbloxLFOutputSettings(port=2, offset=0.0), QbloxLFOutputSettings(port=3, offset=0.0)] sequencers=[QbloxSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_

In [16]:
runcard = Runcard(name="saruman")
runcard

Runcard(name='saruman', instruments=[], instrument_controllers=[])

In [17]:
runcard.instruments = [instrument.to_runcard() for instrument in loaded_instruments]

In [18]:
runcard.add_instrument_controller(qdac2_controller)
runcard.add_instrument_controller(qblox_controller)
runcard.add_instrument_controller(spi_rack_controller)

In [19]:
runcard.save_to("runcard.yml")

In [ ]:
print(qcm.get_parameters())

[<Parameter.TIMEOUT: 'timeout'>, <Parameter.GAIN_I: 'gain_i'>, <Parameter.GAIN_Q: 'gain_q'>, <Parameter.OFFSET_I: 'offset_i'>, <Parameter.OFFSET_Q: 'offset_q'>, <Parameter.HARDWARE_MODULATION: 'hardware_modulation'>, <Parameter.IF: 'intermediate_frequency'>, <Parameter.GAIN_IMBALANCE: 'gain_imbalance'>, <Parameter.PHASE_IMBALANCE: 'phase_imbalance'>]


In [42]:
qcm.set_parameter(parameter=Parameter.OFFSET, value=0.5, output=0)
qcm.set_parameter(parameter=Parameter.GAIN_I, value=0.5, channel=2)
qcm.set_parameter(Parameter.GAIN_I, 0.5, 0)
qcm

QbloxQCM(settings=alias='qcm' timeout=1 outputs=[QbloxLFOutputSettings(port=0, offset=0.5), QbloxLFOutputSettings(port=1, offset=0.0), QbloxLFOutputSettings(port=2, offset=0.0), QbloxLFOutputSettings(port=3, offset=0.0)] sequencers=[QbloxSequencerSettings(id=0, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=0.5, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=1, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=2, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=0.5, gain_q=1.0, offset_i=0.0, offset_q=0.0), QbloxSequencerSettings(id=3, outputs=[0], hardware_modulation=True, intermediate_frequency=500000000.0, gain_imbalance=0.0, phase_imbalance=0.0, gain_i=1.0, gain_q=1.0, offs

In [13]:
wrong_controller = QDevilQDAC2Controller(
    settings=QDevilQDAC2ControllerSettings(alias="wrong_controller", modules=[{"alias": "non_existant", "slot": 0}])
)

In [16]:
loaded_runcard = Runcard.load_from("runcard.yml")
loaded_runcard

Runcard(name='saruman', instruments=[QDevilQDAC2RuncardInstrument(type=<InstrumentType.QDEVIL_QDAC2: 'qdac2'>, settings=QDevilQDAC2Settings(alias='qdac2', dacs=[QDevilQDAC2ChannelSettings(id=0, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=1, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=2, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=3, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<QDevilQDAC2LowPassFilter.DC: 'dc'>), QDevilQDAC2ChannelSettings(id=4, voltage=0.0, span=<QDevilQDAC2Span.LOW: 'low'>, ramping_enabled=True, ramping_rate=1.0, low_pass_filter=<Q

In [14]:
runcard.add_instrument_controller(wrong_controller)

ValidationError: 1 validation error for Runcard
  Value error, Instrument 'non_existant' of controller wrong_controller not found in runcard instruments. [type=value_error, input_value=Runcard(name='saruman', i...slot=0)], reset=True))]), input_type=Runcard]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error