In [1]:
from copy import deepcopy

from qililab.typings.enums import Parameter
from qililab.typings.loop import LoopOptions
from qililab.utils import Loop

[Qibo 0.1.7|INFO|2022-11-24 23:30:02]: Using numpy backend on /CPU:0
[Qibo 0.1.7|WARNING|2022-11-24 23:30:02]: numpy backend uses `np.einsum` and supports CPU only. Consider installing the qibojit or qibotf backends for increased performance and to enable GPU acceleration.


In [3]:
loop = Loop(
    alias="QCM", parameter=Parameter.FREQUENCIES, options=LoopOptions(start=1.0e08, stop=1.5e08, num=10, channel_id=0)
)

In [5]:
loop.to_dict()

{'alias': 'QCM',
 'parameter': 'frequencies',
 'options': {'start': 100000000.0,
  'stop': 150000000.0,
  'num': 10,
  'step': None,
  'logarithmic': False,
  'channel_id': 0,
  'values': None},
 'loop': None}

In [6]:
loop_2 = Loop(
    alias="QCM_2", parameter=Parameter.FREQUENCIES, options=LoopOptions(start=1.0e08, stop=1.5e08, num=10, channel_id=0)
)

In [7]:
loops = Loop(
    alias="QCM",
    parameter=Parameter.FREQUENCIES,
    options=LoopOptions(start=1.0e08, stop=1.5e08, num=10, channel_id=0),
    loop=loop_2,
)

In [9]:
loops.to_dict()

{'alias': 'QCM',
 'parameter': 'frequencies',
 'options': {'start': 100000000.0,
  'stop': 150000000.0,
  'num': 10,
  'step': None,
  'logarithmic': False,
  'channel_id': 0,
  'values': None},
 'loop': {'alias': 'QCM_2',
  'parameter': 'frequencies',
  'options': {'start': 100000000.0,
   'stop': 150000000.0,
   'num': 10,
   'step': None,
   'logarithmic': False,
   'channel_id': 0,
   'values': None},
  'loop': None}}

In [12]:
loop.range

array([1.00000000e+08, 1.05555556e+08, 1.11111111e+08, 1.16666667e+08,
       1.22222222e+08, 1.27777778e+08, 1.33333333e+08, 1.38888889e+08,
       1.44444444e+08, 1.50000000e+08])

In [13]:
loop.ranges

array([[100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0]], dtype=object)

In [14]:
loops.ranges

array([[100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0],
       [100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0]], dtype=object)

In [15]:
input_array = [1, 2, 3, 4, -4.5, 0]

In [17]:
new_loop = Loop(alias="QRM", parameter=Parameter.AMPLITUDE, options=LoopOptions(values=input_array))

In [19]:
new_loop.to_dict()

{'alias': 'QRM',
 'parameter': 'amplitude',
 'options': {'start': 1,
  'stop': 0,
  'num': 6,
  'step': None,
  'logarithmic': False,
  'channel_id': None,
  'values': [1, 2, 3, 4, -4.5, 0]},
 'loop': None}

In [20]:
log_loop = Loop(alias="QCM", parameter=Parameter.GAIN, options=LoopOptions(start=1, stop=10, num=10, logarithmic=True))

In [23]:
log_loop.range

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])