In [1]:
from copy import deepcopy

from qililab.typings.enums import Parameter
from qililab.utils import Loop

[Qibo 0.1.7|INFO|2022-11-15 17:49:31]: Using numpy backend on /CPU:0
[Qibo 0.1.7|WARNING|2022-11-15 17:49:31]: numpy backend uses `np.einsum` and supports CPU only. Consider installing the qibojit or qibotf backends for increased performance and to enable GPU acceleration.


In [2]:
loop = Loop(alias="QCM", parameter=Parameter.FREQUENCIES, start=1.0e08, stop=1.5e08, num=10, channel_id=0)

In [3]:
loop.to_dict()

{'parameter': 'frequencies',
 'start': 100000000.0,
 'stop': 150000000.0,
 'alias': 'QCM',
 'instrument': None,
 'id_': None,
 'num': 10,
 'step': None,
 'loop': None,
 'logarithmic': False,
 'previous': None,
 'channel_id': 0,
 'values': None}

In [4]:
loop.to_array()

array([[100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0]], dtype=object)

In [5]:
loop.range

array([1.00000000e+08, 1.05555556e+08, 1.11111111e+08, 1.16666667e+08,
       1.22222222e+08, 1.27777778e+08, 1.33333333e+08, 1.38888889e+08,
       1.44444444e+08, 1.50000000e+08])

In [6]:
input_array = deepcopy(loop.range)

In [7]:
new_loop = Loop.from_array(parameter=Parameter.AMPLITUDE, alias="QRM", values=input_array)

In [8]:
new_loop.to_array()

array([[100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0]], dtype=object)

In [9]:
new_loop.range

array([1.00000000e+08, 1.05555556e+08, 1.11111111e+08, 1.16666667e+08,
       1.22222222e+08, 1.27777778e+08, 1.33333333e+08, 1.38888889e+08,
       1.44444444e+08, 1.50000000e+08])

In [10]:
new_loop.ranges

array([[100000000.0, 105555555.55555555, 111111111.1111111,
        116666666.66666667, 122222222.22222222, 127777777.77777778,
        133333333.33333334, 138888888.8888889, 144444444.44444445,
        150000000.0]], dtype=object)

In [11]:
new_loop.to_dict()

{'parameter': 'amplitude',
 'start': 100000000.0,
 'stop': 150000000.0,
 'alias': 'QRM',
 'instrument': None,
 'id_': None,
 'num': None,
 'step': None,
 'loop': None,
 'logarithmic': False,
 'previous': None,
 'channel_id': None,
 'values': [100000000.0,
  105555555.55555555,
  111111111.1111111,
  116666666.66666667,
  122222222.22222222,
  127777777.77777778,
  133333333.33333334,
  138888888.8888889,
  144444444.44444445,
  150000000.0]}

In [16]:
log_loop = Loop(alias="QCM", parameter=Parameter.GAIN, start=1, stop=10, num=10, logarithmic=True, channel_id=0)

In [17]:
log_loop.to_array()

array([[1.0, 1.2915496650148839, 1.6681005372000588, 2.154434690031884,
        2.7825594022071245, 3.5938136638046276, 4.641588833612778,
        5.994842503189409, 7.742636826811269, 10.0]], dtype=object)